### PR TITLE
Initial Korean translation + build script patch pull request.

### PR DESCRIPTION
**Pull request by garrettjavalia**
I am a programmer who have read your socket programming guide long time ago.
Its been almost 9 years ago from the first time that I have found your document and it`s korean translation versions
(the korean translation version that I have read was made in 1999)

I tried to translate your document few times and this is the most far achievement I have done through my many trys.

please check this pull request and give me any ideas/opinions.

this pull request has three main changes:

- add korean translation in a form of co-existatable way with original english version.
  it is seperated from the english version, so that translators can keep track of english version and update their translation.
the korean translation is 30% done, and I will finish it in 2 months.
this korean translation uses pretendard font for pdf/html. pretendard`s license allows commercial/non commercial change/selling/distributions except selling font itself. full license text is here. https://github.com/orioncactus/pretendard/blob/main/LICENSE
- fix build error
  the build script was crashing somehow when old_href was None, so I have fixed it.
- improve build script
  the python script were not generating index.html for splitte versions. I fixed it to generate index.html correctly.
  the makefile script did not have any options for src dir, so I added one to support multi langual build. that is SRCDIR option of root makefile script, which uses './src' in default.
  
I want to make a better way to share this translation with other people, and I thought pushing this to main repository could be a way for it.
thank you.

### CODE REVIEW

**Comment by beejjorgensen** [comment]
This is looking generally awesome, but when I try to build the original site on your branch, the encoding is off and the CSS is missing...?

**Comment by garrettjavalia** [comment]
Thank you for checking! I will try to fix it. It would be great if you tell me what is encoding that you have mentioned on the comment.

**Comment by garrettjavalia** [comment]
I have tested the problem by building the english version in my latest branch but I were not able to reproduce the problem. home page were builded fine.
However, It might be the tool chain and build script problem I guess. Below are few things that I have found during the inspecting of problem.

1. The main build command `docker build -t beej-bgnet-builder .` in the root directory fails even in the commit b8b2b756ee59eb7d11b42833321dd572feb824b2 ("up ver" by @beejjorgensen ) which is latest commit that my PR is based on.
2. I had to fix some problems of your build script, but I guess all of those problems were happened by update of build toolchains. (If not, how did the original build scripts could work and generate the website?))
3. So I guess if you were using local toolchain instead of the dockerized one, that could cause the problem due to mismatch of my updated script/files and your toolchain.

please let me know if the dockerized version were still causing problem. ( It should not be the problem but I am using docker in windows.)

I am really thankful for your comment and I'm going to continue the translation work.

**Comment by garrettjavalia** [comment]
I will open pullrequest again someday later when I finish the initial translation. This branch is too messy for a PR.

**Pull request closed without merging**
