### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by d-s-dc**
what-have-you -> what-you-have
automagically   -> automatically

### CODE REVIEW

**Comment by sthagen** [comment]
I would assume that these were no typos.

**Comment by d-s-dc** [comment]
guess I have to own my poor english.

**Comment by sthagen** [comment]
> guess I have to own my poor english.

No, no, that was not intended -I just assume that these expressions were consciously chosen by the author  - as a literal device

**Comment by d-s-dc** [comment]
Yeah, I get it. I was little embarrassed after knowing they had meanings and not typos.

**Comment by d-s-dc** [comment]
Hey since you are active, can you clear a small doubt of mine. It is a weird place I know, but didn't find it on the internet.

INADDR_ANY can be used to listen to all the IP's available on the machine's interface. So, a server cannot listen to all the IPs in the world but only the ones on my machine. Is the case similar with bind command? Can it only bind a socket to IP's available on the interface? I have been trying some random IPs with no success.

**Comment by beejjorgensen** [comment]
No worries, better safe than sorry! But no, they're deliberate! :)

**Pull request closed without merging**
